src/Entity/Representations.php
<?php

namespace App\Entity;

use App\Repository\RepresentationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;

#[ORM\Entity(repositoryClass: RepresentationsRepository::class)]
#[ORM\Table(name:'representations')]

class Representations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Shows::class, inversedBy: 'representations')]
    #[ORM\JoinColumn(nullable: false, name :'show_id', referencedColumnName :'id', onDelete :'RESTRICT')]
    private $the_show;

    #[ORM\Column(type: 'datetime')]
    private $schedule;

    #[ORM\ManyToOne(targetEntity: Locations::class, inversedBy: 'representations')]
    #[ORM\JoinColumn(name :'location_id', referencedColumnName :'id', onDelete :'RESTRICT')]
    private $the_location;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheShow(): ?Shows
    {
        return $this->the_show;
    }

    public function setTheShow(?Shows $the_show): self
    {
        $this->the_show = $the_show;

        return $this;
    }

    public function getSchedule(): ?\DateTimeInterface
    {
        return $this->schedule;
    }

    public function setSchedule(\DateTimeInterface $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }

    public function getTheLocation(): ?Locations
    {
        return $this->the_location;
    }

    public function setTheLocation(?Locations $the_location): self
    {
        $this->the_location = $the_location;

        return $this;
    }
}

src/Controller/RepresentationsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Representations;
use App\Repository\RepresentationsRepository;
use Doctrine\Persistence\ManagerRegistry;


class RepresentationsController extends AbstractController
{
    #[Route('/representations', name: 'app_representations')]
    public function index(RepresentationsRepository $repository): Response
    {
        //$repository = $this->getDoctrine()->getRepository(Representations::class);
        $representations = $repository->findAll();
        
        return $this->render('representations/index.html.twig', [
            'representations' => $representations,
            'resource' => 'représentations',
        ]);
    }

    /**
     * @Route("/representations/{id}", name="representations_show")
     */
    public function show(ManagerRegistry $doctrine, $id)
    {
        $repository = $doctrine->getRepository(Representations::class);
        $representation = $repository->find($id);

        return $this->render('representations/show.html.twig', [
            'representation' => $representation,
        ]);
    }

}

templates/representations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des représentations{% endblock %}

{% block body %}
    <h1>Liste des {{ resource }}</h1>

    <ul>
    {% for representation in representations %}
        <li><a href="{{ path('representations_show', { id: representation.id }) }}">{{ representation.theShow.title }}</a>
            {% if representation.theLocation %}
            - <span>{{ representation.theLocation.designation }}</span>
            {% endif %}
            - <datetime>{{ representation.schedule|date('d-m-Y H:i') }}</datetime>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/representations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'une représentation{% endblock %}

{% block body %}
    <article>
        <h1>Représentation du {{ representation.schedule|date('d/m/Y') }} à {{ representation.schedule|date('G:i') }}</h1>
        <p><strong>Spectacle:</strong> {{ representation.theShow.title }}</p>

        <p><strong>Lieu:</strong> 
        {% if representation.theLocation %}
        {{ representation.theLocation.designation }}
        {% elseif representation.theShow.location %}
        {{ representation.theShow.location.designation }}
        {% else %}
        <em>à déterminer</em>
        {% endif %}
        </p>
    </article>

    <nav><a href="{{ path('app_representations') }}">Retour à l'index</a></nav>
{% endblock %}